// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3K3D14OEmqXpNE2ZBInv-lzpjQ6SPn8',
    appId: '1:542841366036:web:c3be28660904489ed1a901',
    messagingSenderId: '542841366036',
    projectId: 'flutterapplication2005',
    authDomain: 'flutterapplication2005.firebaseapp.com',
    storageBucket: 'flutterapplication2005.firebasestorage.app',
    measurementId: 'G-N99XFGXJGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-sR410ZZGuuKDnxVnmYlgMxMOG7k3brI',
    appId: '1:542841366036:android:2318897afd82baa8d1a901',
    messagingSenderId: '542841366036',
    projectId: 'flutterapplication2005',
    storageBucket: 'flutterapplication2005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSwHcUvV_8uaOMFVF8jW2opZSQtx1QSD4',
    appId: '1:542841366036:ios:d93c05613822ca2cd1a901',
    messagingSenderId: '542841366036',
    projectId: 'flutterapplication2005',
    storageBucket: 'flutterapplication2005.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSwHcUvV_8uaOMFVF8jW2opZSQtx1QSD4',
    appId: '1:542841366036:ios:d93c05613822ca2cd1a901',
    messagingSenderId: '542841366036',
    projectId: 'flutterapplication2005',
    storageBucket: 'flutterapplication2005.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq3K3D14OEmqXpNE2ZBInv-lzpjQ6SPn8',
    appId: '1:542841366036:web:0eb7a2943e9805aed1a901',
    messagingSenderId: '542841366036',
    projectId: 'flutterapplication2005',
    authDomain: 'flutterapplication2005.firebaseapp.com',
    storageBucket: 'flutterapplication2005.firebasestorage.app',
    measurementId: 'G-1D9GGBLBMT',
  );
}
